[tool.poetry]
name = "voyagis"
version = "0.1.0"
description = "Voyagis"
authors = ["gnart"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
